# 예외처리(3)

---

### 9. 자동 자원 반환 -try-with-resourceans

Try-with-resource문은 try-catch문의 변형으로 이 구문은 입출력(I/O)과 관련된 클래스를 사용할 때 유용하다. 주로 입출력에 사용되는 클래스중에는 resource를 반환하기 때문에 닫아줘야하는 것들이 있다.

```java
try {
  fis = new FileInputStream("score.dat");
  dis = new DataInputStream(fis);
} catch (IOException ie) {
  ie.printStackTrace();
} finally {
  dis.close();
}
```

위의 코드는 DataInputStream을 사용해서 파일로부터 데이터를 읽는 코드인데, 데이터를 읽는 도중에 예외가 발생하더라도 DataInputStream이 닫히도록 finally블럭에 close()를 넣어준다. 여기서 문제는 close도 예외를 발생시킨다.

```java
try {
  fis = new FileInputStream("score.dat");
  dis = new DataInputStream(fis);
} catch (IOException ie) {
  ie.printStackTrace();
} finally {
  try{
  	if(dis != null)
      dis.close();
  } catch (IOException ie) {
    ie.printStackTrace();
  }
}
```

finally블럭 안에 try문을 추가하여 close의 예외를 처리하도록 하였다. 그런 이런식으로 짜게되면 코드가 복잡해진다. 또 try, finally모두 예외가 뜬다면 try블럭에 예외는 무시해도 된다.

이 점을 개선하기 위해 try-with-resource문이 나온것이다.

```java
try(FileInputStream fis = new FileInputStream("score.dat")
   DataInputStream dis = new DataInputStream(fis)) {
  while(true){
    score = dis.readInt();
    System.out.println("점수의 총합은 " + sum + "입니다");
    sum += score;
  }
} catch (EOFExeption e) {
  System.out.println("점수의 총합은 " + sum + "입니다");
} catch (IOException ie) {
  ie.printStackTrace();
}
```

Try-with-resource문의 괄호()안에 객체를 생성하는 문장을 넣으면, 이 객체는 따로 close()를 호출하지 않아도 try블럭을 벗어나는 순간 자동적으로 close된다. 그 뒤에 catch블럭 또는 finally블럭이 수행된다.

그런데 아까도 말했듯 close는 예외를 발생시킬 수 있다. 그렇다면 자동 생성된 close에서 예외가 발생하면 어떻게 될까?

```java
class TryWithResourceEx{
    public static void main(String[] args) {
        try (CloseableResource cr = new CloseableResource()) {
            cr.exceptionWork(false);
        }catch (WorkException e) {
            e.printStackTrace();
        }catch (CloseException e) {
            e.printStackTrace();
        }
        System.out.println();

        try (CloseableResource cr = new CloseableResource()) {
            cr.exceptionWork(true);
        }catch (WorkException e) {
            e.printStackTrace();
        }catch (CloseException e) {
            e.printStackTrace();
        }
    }
}
class CloseableResource implements AutoCloseable {
    public void exceptionWork(boolean exception) throws WorkException {
        System.out.println("exceptionWork("+exception+")가 호출됨");

        if(exception)
            throw new WorkException("WorkException 발생!!");
    }
    public void close() throws CloseException {
        System.out.println("close()가 호출됨");
        throw new CloseException("CloseException 발생!!");
    }
}
class WorkException extends Exception{
    WorkException(String msg) { super(msg); }
}
class CloseException extends Exception {
    CloseException(String msg) { super(msg); }
}
/*
출력결과 :
seogeonhui@seogeoncBookPro src % java TryWithResourceEx 
exceptionWork(false)가 호출됨
close()가 호출됨
CloseException: CloseException 발생!!
	at CloseableResource.close(TryWithResourceEx.java:30)
	at TryWithResourceEx.main(TryWithResourceEx.java:5)

exceptionWork(true)가 호출됨
close()가 호출됨
WorkException: WorkException 발생!!
	at CloseableResource.exceptionWork(TryWithResourceEx.java:26)
	at TryWithResourceEx.main(TryWithResourceEx.java:13)
	Suppressed: CloseException: CloseException 발생!!
		at CloseableResource.close(TryWithResourceEx.java:30)
		at TryWithResourceEx.main(TryWithResourceEx.java:14)
*/
```

main메서드에 두 개의 try-catch문이 있는데, 첫 번째 것은 close()에서만 예외를 발생시키고, 두 번째 것은 exceptionWork()와 close()에서 모두 예외를 발생 시킨다. 

첫 번째는 예외를 발생했을 때와 같은 형태로 출력되었지만, 두 번째는 출력형태가 다르다. 먼저 발생한 예외는 일반적인 예외와 똑같이 출력하고, 두 번째는 exceptionWork()에서 발생한 예외에 대한 내용이고 close()에서 발생한 예외는 '억제된(suppressed)'이라는 의미의 머리말이과 함께 출력되었다.

예외는 두가지 이상이 동시에 발생할 수 있지 않기 때문에, 실제 발생한 예외를 WorkException으로 하고, CloseException은 억제된 예외로 다룬다.

Throwable에는 억제된 예외와 관련된 다음과 같은 메서드가 정의되어 있다.

```java
void addSuppressed(Throwable exception){ }    //억제된 예외를 추가
Throwable[] getSuppressed();                  //억제된 예외 (배열)를 반환
```

### 10. 사용자정의 예외 만들기

기존의 정의된 예외 클래스 외에 필요에 따라 프로그래머가 새로운 예외 클래스를 정의하여 사용할 수 있다. 보통 Exception클래스 또는 RuntimeException클래스로부터 상속받아 클래스스를 만들지만, 필요에 따라서 알맞은 예외 클래스를 선택할 수 있다.

```java
class MyException extends Exception {
  MyException(String msg) {
    super(msg);
  }
}
```

Exception클래스로부터 상속받아서 MyException클래스를 만들었다. 필요하다면, 멤버변수나 메서드를 추가할 수 있다. Exception클래스와 같은 경우 생성 시에 String을 매개변수로 받아 메시지를 저장할 수 있다. 그러나 우리가 정의한 예외 클래스도 메시지를 저장할 수 있으려면 String을 매개변수로 받는 생성자를 추가해주어야함.

```java
class MyException extends Exception {
  private final int ERR_CODE;
  
  MyException(String msg, int errCode) {
    super(msg);
    ERR_CODE = err_Code;
  }
  MyException(String msg) {
    this(msg, 100);
  }
  public int getErrCode() {
    return ERR_CODE;
  }
}
```

이전에 코드를 좀더 개선하여 메시지뿐만 아닌 에러코드 값도 저장할 수 있도록 만들어주었다. 

기존의 예외 클래스는 주로 Exception을 상속받아서 'checked예외'로 작성하는 경우가 많았지만, 요즘은 예외처리를 선택적으로 할 수 있도록 RuntimeException을 상속받아서 작성하는 쪽으로 바뀌었다. 만약 checked예외로 할 경우 try-catch문을 사용해야 하여 코드가 복잡해지기 때문이다.

예외처리를 강제하도록 한 이유는 프로그래밍경험이 적은 사람들도 보다 견고한 프로그램을 작성할 수 있게 유도하기 위한 것인데, 이는 옛 자바의 대우가 소형 가전기기, 데스크탑에서 실행될 것이라고 생각했지만 현재는 모바일, 웹 프로그래밍같은일에 사용되어 환경이 바뀌어 예외처리가 필수가 아니게 됬다.

```java
public class NewExceptionTest {
    public static void main(String[] args) {
        try {
            startInstall();
            copyFile();
        } catch (SpaceException e) {
            System.out.println("에러메세지 : " + e.getMessage());
            e.printStackTrace();
            System.out.println("공간을 확보한 후에 다시 설치하시기 바랍니다.");
        } catch (MemoryException me) {
            System.out.println("에러메시지 : " + me.getMessage());
            me.printStackTrace();
            System.gc();
            System.out.println("다시 설치를 시도하세요");
        } finally {
            deleteTempFiles();
        }
    }

    static void startInstall() throws SpaceException, MemoryException {
        if(!enoughSpace()) {
            throw new SpaceException("설치할 공간이 부족합니디");
        }
        if(!enoughMemory()) {
            throw new MemoryException("메모리가 부족합니다");
        }
    }

    static void copyFile() {
        /*파일복사 코드*/
    }
    static void deleteTempFiles() {
        /*임시파일들을 삭제하는 코드를 적는다*/
    }

    static boolean enoughSpace() {
        //설치하는데 필요한 공간이 있는지 확인하는 코드
        return false;
    }
    static boolean enoughMemory() {
        //설치하는데 필요한 메서리공간이 있는지 확인하는 코드
        return true;
    }
}

class SpaceException extends Exception {
    SpaceException(String msg) {
        super(msg);
    }
}

class MemoryException extends Exception {
    MemoryException(String msg) {
        super(msg);
    }
}
/*
출력결과 :
seogeonhui@seogeoncBookPro src % java NewExceptionTest 
에러메세지 : 설치할 공간이 부족합니디
SpaceException: 설치할 공간이 부족합니디
	at NewExceptionTest.startInstall(NewExceptionTest.java:22)
	at NewExceptionTest.main(NewExceptionTest.java:4)
공간을 확보한 후에 다시 설치하시기 바랍니다.
*/
```

위 코드는 MemoryException과 SpaceException, 이 두 개의 사용자정의 예외 클래스를 새로 만들어서 사용했다. Space Exception은 프로그램을 설치하려는 곳에 충분한 공간이 없을 경우에 발생하도록 되어 있으며, MemoryException은 설치작업을 수행하는데 메모리가 충분히 확보하지 않았을 경우에 발생하도록 하였다.

이 두 예외는 startInstall()을 수행하는 동안에 발생할 수 있으며, enoughSpace()와 enoughMemory()의 실행결과에 따라서 발생하는 예외의 종류가 달라지도록 했다.

이번 예제에서 enoughSpace()와 enoughMemory()는 단순히 false와 true를 각각 반환하도록 되어 있지만 설치공간을 확인하는 기능이 있다고 가정함.

### 11. 예외 되던지기(exception re-throwing)

한 메서드에서 발생할 수 있는 예외가 여럿인 경우, 몇 개는 try-catch문을 통해서 메서드 내에서 자체적으로 처리하고, 그 나머지는 선언부에 지정하여 호출한 메서드에서 처리하도록 할 수 있다. 그리고 심지어는 단 하나의 예외에 대해서도 예외가 발생한 메서드와 호출한 메서드, 양쪽에서 처리하도록 할 수 있다. 

이것은 예외를 처리한 후에 인위적으로 다시 발생시키는 방법을 통해서 가능한데, 이것을 **'예외 되던지기(exception re-throwing)'**라고 한다.

```java
class ExceptionEx17 {
  public static void main(String args[]) {
    try {
      method1();
    } catch (Exception e) {
      System.out.println("main메서드에서 예외가 처라되었습니다.");
    }
  }
  static void method1() throws Exception {
    try {
      throws new Exception();
    } catch (Exception e) {
      System.out.println("method1메서드에서 예외가 처리되었습니다.");
      throw e;
    }
  }
}
/*
method1메서드에서 예외가 처리되었습니다.
main메서드에서 예외가 처리되었습니다.
*/
```

이 방법은 하나의 예외에 대해서 예외가 발생한 메서드와 이를 호출한 메서드 양쪽 모두에서 처리해줘야 할 작업이 있을 때 사용한다. **이 때 주의할 점은 예외가 발생할 메서드에서는 try-catch문을 사용해서 예외처리를 해줌과 동시에 메서드의 선언부에 발생할 예외를 throws에 지정해줘야한다.**

출력결과를 통해 알 수 있는 사실은 main의 catch블럭과 method1의 catch블럭을 모두 실행한 모습을 볼 수 있다. 이때 만약 반환값이 있는 retrun문이라면 예외가 발생했을 경우에도 값을 반환해야한다.

```java
static int method1() {
  try{
    System.out.println("method1()이 호출되었습니다");
    return 0;    //현제 실행중인 메서드를 종료
  } catch (Exception e){
    e.printStackTrace();
    return 1;    //catch블럭에도 retrun은 필요함
  } finally {
    System.out.println("method1()의 finally블럭이 실행되었습니다.");
  }
}
```

또는 catch블럭에서 예외 되던지기를 해서 호출한 메서드로 예외를 전달하면, return문이 없어도 된다. 그래서 검증에서도 assert문 대신 AssertError를 생성해서 던진다.

```java
static int method1() throws Exception{
  try {
    System.out.println("method1()이 호출되었습니다");
    return 0;
  } catch (Exception e) {
    e.printStackTrace();
    throw new Exception();    //예외 되던지기를 사용하면 return문이 없어도 된다. 대신 예외를 호출한 메서드로 전달
  } finally {
    System.out.println("method1()의 finally블럭이 실행되었습니다.");
  }
}
```

### 12. 연결된 예외(chained exception)

한 예외가 다른 예외를 발생시킬 수도 있다. 예를 들어 **예외 A가 예외 B를 발생시켰다면, A를 B의 '원의 예외(cause exception)'라고 한다.** 전에 나왔던 프로그램을 설치하는 프로그램을 일부를 변경한 것으로, SpaceException을 윈인 에외로 하는 InstallException을 원인예외로 하는 InstallException을 발생시키는 방법을 보여준다.

```java 
try {
  statInstall();
  copyFile();
} catch (SpaceException e) {
  InstallException ie = new InstallException("설치중 오류발생");
  ie.initCause(e);
  throw ie;
} catch (MemoryException me) {
  ...
}
```

먼저 InstallException을 생성한 후에, initCause()로 SpaceException을 InstallException의 원인 예외로 등록한뒤 thorw로 이 예외를 던진다.

initCause()는 Exception클래스의 조상인 Throwable클래스에 정의되어 있기 떄문에 모든 예외에서 사용이 가능하다.

1. **Throwable iniCause(Throwable cause)** : 지정한 얘외를 원인 예외로 등록
2. **Throwable getCuase()** : 원인 예외를 반환

위와 같이 번거롭게 예외를 처리하지 않고 원인예외로 등록하여 하는 이유는 여러가지 예외를 하나의 부류로 묶어서 다루기 위해서이다.

그러나 위 코드에서 InstallException을 SpaceException과 MemoryException의 부모로 정의하여 catch블럭을 만들면 안된다. 그 이유는 예외가 발생했을 때 그예외가 어떠한 예외인지 구분할 수 없기 때문이다. 또한 두 클래스를 상속관계로 바꾸어 줘야한다는 부담도 크다.

```java
try{
  startInstall();
  copyFiles();
} catch (InstallException e) {
  e.printStackTrace();
}
```

또한 checked예외를 원인예외를 통해 unchecked예외로 바꿀 수 있도록하기 위함도 있다. 위에서 말했듯 현재 자바개발을 할 경우 unchecked예외를 더 많이 필요하게되었다. 

```java
static void startInstall() throws SpaceException, MemoryException {
  if(!enoughSpace()) throw new SpaceException("설치공간이 부족합니다.");
  if(!enoughMemory()) throw new MemoryException("메모리가 부족합니다.");
}
```

위 코드를 보면 MemoryException은 Exception의 자손으로 checked예외이다. 즉 반드시 예외 처리를 해주어야 한다.

```java
static void startInstall() throws SpaceException {
  if(!enoughSpace()) 
    throw new SpaceException("설치공간이 부족합니다");
  if(!enoughMemory()) 
    throw new RuntimeException(new MemoryException("메모리가 부족합니다"));
}
```

아까전 위에 코드같은 경우는 Exception의 자손으로 무조건 예외처리를 해주어야만 하는 startInstall이었지만 지금은 RuntumeException으로 감싸서 unchecked예외로 만들어주어 예외처리를 필수로 만들어주지 않았다.

위 코드는 아까와 달리 initCause를 사용하지 않고 RuntimeException의 생성자를 사용했다. 

```java
RuntimeException(Throwable cause)    //원인 예외를 등록하는 생성자
```

다음은 지금 껏나온 모든 예외처리를 모아놓은 예제입니다. 천천히 이해해보세여!

```java
public class ChainExceptionEx {
    public static void main(String[] args) {
        try {
            install();
        } catch (InstallException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    static void install() throws InstallException {
        try {
            startInstall();
            copyFiles();
        } catch (SpaceException1 se) {
            InstallException ie = new InstallException("설치중 예외발생");
            ie.initCause(se);
            throw ie;
        } catch (MemoryException1 me) {
            InstallException ie = new InstallException("설치중 예외발생");
            ie.initCause(me);
            throw ie;
        } finally {
            deleteFiles();
        }
    }
    static void startInstall() throws SpaceException1, MemoryException1 {
        if(!enoughSpace()) {
            throw new SpaceException1("설치 공간이 부족합니다.");
        }
        if(!enoughMemory()) {
            throw new MemoryException1("메모리가 부족합니다.");
            //throw new RuntimeException(new MemoryException("메모리가 부족합니다"));
            //이렇게 선언시 선언부에 MemoryException 은 제거 가능
        }
    }

    static void copyFiles() {/*파일 복사*/}
    static void deleteFiles() {/*파일 삭제*/}

    static boolean enoughSpace() {
        //설치공간이 충분한지 확인
        return false;
    }
    static boolean enoughMemory() {
        //메모리가 충분한지 확인
        return true;
    }
}

class InstallException extends Exception {
    InstallException(String msg) {
        super(msg);
    }
}

class SpaceException1 extends Exception {
    SpaceException1(String msg) {
        super(msg);
    }
}

class MemoryException1 extends Exception {
    MemoryException1(String msg) {
        super(msg);
    }
}
/*
출력결과 :
InstallException: 설치중 예외발생
	at ChainExceptionEx.install(ChainExceptionEx.java:16)
	at ChainExceptionEx.main(ChainExceptionEx.java:4)
Caused by: SpaceException1: 설치 공간이 부족합니다.
	at ChainExceptionEx.startInstall(ChainExceptionEx.java:29)
	at ChainExceptionEx.install(ChainExceptionEx.java:13)
	... 1 more
*/
```

---

